# Generated by Django 5.1.6 on 2025-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
