# Generated by Django 5.1.6 on 2025-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
