# Generated by Django 5.1.6 on 2025-03-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='text',
            new_name='type',
        ),
    ]
