# Generated by Django 5.1.6 on 2025-03-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_text_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_year_manufacture',
            field=models.DateField(blank=True, null=True),
        ),
    ]
