# Generated by Django 5.1.6 on 2025-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_film_year_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', '⭐️'), ('2', '⭐️⭐️'), ('3', '⭐️⭐️⭐️'), ('4', '⭐️⭐️⭐️⭐️'), ('5', '⭐️⭐️⭐️️⭐️⭐️')], max_length=1, null=True),
        ),
    ]
