# Generated by Django 5.1.6 on 2025-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, choices=[('️️️⭐️', '⭐️'), ('⭐️⭐️', '⭐️⭐️'), ('⭐️⭐️⭐️', '⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️⭐️'), ('⭐️⭐️⭐️⭐️⭐️', '⭐️⭐️⭐️️⭐️⭐️')], max_length=10, null=True),
        ),
    ]
