# Generated by Django 5.1.6 on 2025-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'MovieType',
                'verbose_name_plural': 'MovieType',
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movie'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_year_manufacture',
            field=models.DateField(blank=True, null=True, verbose_name='Film created year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, choices=[('️️️⭐️', '1'), ('⭐️⭐️', '2'), ('⭐️⭐️⭐️', '️3'), ('⭐️⭐️⭐️⭐️', '4'), ('⭐️⭐️⭐️⭐️⭐️', '5')], max_length=10, null=True, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(upload_to='', verbose_name='video_file'),
        ),
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(to='movies.movie')),
            ],
            options={
                'verbose_name': 'Top Movie',
                'verbose_name_plural': 'Top Movie',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ManyToManyField(to='movies.movietype'),
        ),
    ]
