# Generated by Django 5.1.6 on 2025-03-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
