# Generated by Django 5.1.6 on 2025-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
