# Generated by Django 5.1.6 on 2025-03-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movie_film_year_manufacture_alter_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='title_translations',
            field=models.JSONField(default=dict, help_text="Переводы названия фильма. Пример: {'ru': 'Фильм', 'en': 'Movie', 'uz': 'Film'}"),
        ),
    ]
