# Generated by Django 5.1.6 on 2025-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_remove_movie_title_movie_title_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title_translations',
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название (англ)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название (рус)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_uz',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название (узб)'),
        ),
    ]
