# Generated by Django 5.1.6 on 2025-03-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_movie_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
    ]
